# Generated by Django 5.2.4 on 2025-07-08 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do alimento', max_length=100)),
                ('serving_size_grams', models.DecimalField(decimal_places=2, help_text='Tamanho da porção em gramas', max_digits=7)),
                ('calories', models.IntegerField(help_text='Calorias por porção')),
                ('protein', models.DecimalField(decimal_places=2, help_text='Proteínas por porção (g)', max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carboidratos por porção (g)', max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, help_text='Gorduras por porção (g)', max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.DecimalField(decimal_places=2, help_text='Quantidade consumida em gramas', max_digits=7)),
                ('date', models.DateField(auto_now_add=True, help_text='Data do registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories.food')),
            ],
        ),
    ]
