# Generated by Django 5.2.4 on 2025-07-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='dailylog',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Ordem do alimento na lista do dia'),
        ),
    ]
