# Generated by Django 5.2.4 on 2025-07-08 23:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre o treino')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(help_text='Número da série')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Peso utilizado (kg)', max_digits=6)),
                ('reps', models.PositiveIntegerField(help_text='Número de repetições')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre esta série')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.exercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='logbook.workoutsession')),
            ],
            options={
                'ordering': ['exercise', 'set_number'],
                'unique_together': {('workout_session', 'exercise', 'set_number')},
            },
        ),
    ]
