# Generated by Django 5.2.4 on 2025-07-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_exercise_unique_exercise_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído')], default='active', max_length=10),
        ),
    ]
