# Generated by Django 5.2.4 on 2025-07-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_alter_workoutsession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Ordem do exercício no treino')),
                ('sets', models.PositiveIntegerField(help_text='Número de séries para este treino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.exercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='logbook.workoutsession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workout_session', 'exercise')},
            },
        ),
    ]
